FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache libc6-compat
RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml ./
COPY next.config.mjs postcss.config.mjs tailwind.config.ts tsconfig.json ./

COPY ./prisma ./prisma
COPY ./.env ./.env

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

RUN chown -R nextjs:nodejs /app
USER nextjs

RUN pnpm install --frozen-lockfile

EXPOSE 5555

CMD ["pnpm", "exec", "prisma", "studio", "--port", "5555"]